command_timeout = 600

add_newline = true
format = "$conda$python[$directory$git_branch$git_status]($style)$line_break$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
repo_root_style = "bold cyan"
format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format = '[$all_status]($style)'
style = "cyan"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""


[conda]
format = "([\\($environment\\)]($style) )"
style = "bold green"
ignore_base = true

[python]
format = '([\($virtualenv\)]($style) )'
style = "yellow bold"
